import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create transporter
const createTransporter = () => {
    return nodemailer.createTransport({
        service: process.env.SMTP_SERVICE || 'gmail',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD
        }
    });
};

// Email templates (изменяем только subject в highPriorityAlert)
const emailTemplates = {
    newRentalInquiry: (contactData, siteData) => ({
        subject: `🎯 New Rental Inquiry: ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #667eea; }
          .badge { background: #667eea; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚀 New Website Rental Inquiry</h1>
            <p>A potential client is interested in renting your website</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>📋 Inquiry Summary</h3>
              <p><strong>Website:</strong> ${siteData.title}</p>
              <p><strong>Category:</strong> <span class="badge">${siteData.category}</span></p>
              <p><strong>Monthly Price:</strong> $${siteData.price}</p>
              <p><strong>Inquiry Date:</strong> ${new Date().toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>
            </div>

            <div class="info-card">
              <h3>👤 Client Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              ${contactData.company ? `<p><strong>Company:</strong> ${contactData.company}</p>` : ''}
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #667eea;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Actions</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Reply to Client</a>
                <a href="tel:${contactData.phone || ''}" class="button" style="background: #28a745;">📞 Call Client</a>
              </p>
              <p><small>Client timezone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}</small></p>
            </div>

            <div class="info-card">
              <h3>📊 Website Details</h3>
              <p><strong>Features:</strong> ${siteData.features?.join(', ') || 'No specific features listed'}</p>
              <p><strong>Technologies:</strong> ${siteData.technologies?.join(', ') || 'Not specified'}</p>
              ${siteData.demoUrl ? `<p><strong>Demo:</strong> <a href="${siteData.demoUrl}">View Live Demo</a></p>` : ''}
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Admin System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    newContactMessage: (contactData) => ({
        subject: `📧 New Contact Form Submission: ${contactData.subject || 'General Inquiry'}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff6b6b; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #ff6b6b; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📬 New Contact Message</h1>
            <p>Someone reached out through your website contact form</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>👤 Sender Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Subject:</strong> ${contactData.subject || 'Not specified'}</p>
              <p><strong>Received:</strong> ${new Date().toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        })}</p>
            </div>

            <div class="info-card">
              <h3>💬 Message Content</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #ff6b6b; white-space: pre-wrap;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Response</h3>
              <p>
                <a href="mailto:${contactData.email}?subject=Re: ${contactData.subject || 'Your Inquiry'}" class="button">
                  📧 Reply to Message
                </a>
              </p>
              <p><small>Response recommended within 24 hours</small></p>
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Contact System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    highPriorityAlert: (contactData, siteData) => ({
        subject: `🚨 URGENT: Rental Inquiry - ${siteData.title}`, // Убрали "HIGH PRIORITY"
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff4757 0%, #ff3742 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #fff5f5; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff4757; border: 2px solid #ff4757; }
          .urgent-badge { background: #ff4757; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; display: inline-block; margin-bottom: 10px; }
          .button { background: #ff4757; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 5px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚨 URGENT: Rental Inquiry</h1> <!-- Убрали "High Priority" -->
            <p>Immediate attention required for this rental request</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <div class="urgent-badge">⚠️ URGENT</div> <!-- Изменили текст бейджа -->
              <h3>📋 Urgent Rental Request</h3>
              <p><strong>Website:</strong> ${siteData.title} ($${siteData.price}/month)</p>
              <p><strong>Client:</strong> ${contactData.name} - ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>

            <div class="info-card">
              <h3>🎯 Immediate Actions Required</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Email Client</a>
                ${contactData.phone ? `<a href="tel:${contactData.phone}" class="button" style="background: #2ed573;">📞 Call Now</a>` : ''}
              </p>
              <p><strong>Response Time:</strong> Recommended within 1-2 hours</p>
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #fff1f1; padding: 15px; border-radius: 5px; border-left: 3px solid #ff4757;">
                ${contactData.message}
              </p>
            </div>
          </div>
        </div>
      </body>
      </html>
    `
    }),
    rentalExpiringSoon: (contactData, siteData) => ({
        subject: `⏰ Rental Expiring Soon: ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff9f43 0%, #ff9f43 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #fffaf0; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff9f43; }
          .button { background: #ff9f43; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>⏰ Rental Expiring Soon</h1>
            <p>Your website rental period is about to expire</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>📋 Rental Details</h3>
              <p><strong>Website:</strong> ${siteData.title}</p>
              <p><strong>Monthly Price:</strong> $${siteData.price}</p>
              <p><strong>Expiration Date:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>
              <p><strong>Days Remaining:</strong> ${contactData.daysRemaining} days</p>
            </div>

            <div class="info-card">
              <h3>💳 Renew Your Rental</h3>
              <p>To continue using ${siteData.title}, please make a payment to extend your rental period.</p>
              <p><strong>Next Payment Amount:</strong> $${siteData.price}</p>
              <a href="mailto:support@rentalsite.com?subject=Renewal: ${siteData.title}" class="button">
                📧 Contact Support to Renew
              </a>
            </div>

            <div class="info-card">
              <h3>📞 Need Assistance?</h3>
              <p>If you have any questions about your rental or payment, please contact our support team.</p>
              <p><strong>Email:</strong> rentalsite@gmail.com</p>
              <p><strong>Phone:</strong> +1 (555) 123-4567</p>
            </div>
          </div>

          <div class="footer" style="text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px;">
            <p>This is an automated reminder from RentalSite</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    // Обновленный шаблон adminRentalExpiring
    adminRentalExpiring: (contactData, siteData) => ({
        subject: `⚠️ Rental Expiring Soon: ${contactData.name} - ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { 
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
            line-height: 1.6; 
            color: #333; 
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
          }
          .container { 
            max-width: 700px; 
            margin: 0 auto; 
            padding: 20px;
            background-color: #ffffff;
          }
          .header { 
            background: linear-gradient(135deg, #ff9f43 0%, #ff7b00 100%); 
            color: white; 
            padding: 30px; 
            text-align: center; 
            border-radius: 10px 10px 0 0;
          }
          .header h1 {
            margin: 0;
            font-size: 28px;
            font-weight: 600;
          }
          .header p {
            margin: 10px 0 0;
            font-size: 16px;
            opacity: 0.9;
          }
          .content { 
            padding: 30px; 
            border-radius: 0 0 10px 10px;
            border: 1px solid #e9ecef;
            border-top: none;
          }
          .alert-box {
            background: #fff9e6;
            border: 2px solid #ffc107;
            border-left: 5px solid #ffc107;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 25px;
          }
          .alert-title {
            color: #856404;
            font-weight: 600;
            font-size: 18px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
          }
          .info-card { 
            background: #f8f9fa; 
            padding: 20px; 
            margin: 15px 0; 
            border-radius: 8px; 
            border-left: 4px solid #007bff;
          }
          .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin-top: 15px;
          }
          .info-item {
            margin-bottom: 12px;
          }
          .info-label {
            color: #6c757d;
            font-weight: 500;
            font-size: 14px;
            margin-bottom: 5px;
            display: block;
          }
          .info-value {
            color: #212529;
            font-weight: 600;
            font-size: 16px;
          }
          .days-badge {
            display: inline-block;
            background: ${contactData.daysRemaining <= 1 ? '#dc3545' : contactData.daysRemaining <= 3 ? '#fd7e14' : '#ffc107'};
            color: white;
            padding: 6px 16px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 14px;
            margin-left: 10px;
          }
          .button-container {
            text-align: center;
            margin: 30px 0 20px;
          }
          .button { 
            background: #007bff; 
            color: white; 
            padding: 14px 32px; 
            text-decoration: none; 
            border-radius: 6px; 
            font-weight: 600;
            font-size: 16px;
            display: inline-block;
            margin: 0 10px;
            transition: background-color 0.3s;
          }
          .button:hover {
            background: #0056b3;
            color: white;
            text-decoration: none;
          }
          .button-contact {
            background: #28a745;
          }
          .button-contact:hover {
            background: #1e7e34;
          }
          .footer {
            text-align: center; 
            margin-top: 30px; 
            padding: 20px; 
            color: #6c757d; 
            font-size: 14px;
            border-top: 1px solid #e9ecef;
          }
          .footer p {
            margin: 5px 0;
          }
          .highlight {
            color: #dc3545;
            font-weight: 600;
          }
          .date-detail {
            font-size: 15px;
            color: #495057;
            margin-top: 5px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>⚠️ Rental Expiring Soon</h1>
            <p>Client rental period is about to expire - Immediate action required</p>
          </div>
          
          <div class="content">
            <div class="alert-box">
              <div class="alert-title">
                ⏰ Urgent Notification
                <span class="days-badge">
                  ${contactData.daysRemaining === 1 ? '1 DAY LEFT' :
            contactData.daysRemaining === 0 ? 'EXPIRES TODAY' :
                `${contactData.daysRemaining} DAYS LEFT`}
                </span>
              </div>
              <p style="color: #856404; margin: 0;">
                The rental period for <strong>${siteData.title}</strong> will expire soon. 
                Please contact the client to arrange payment extension.
              </p>
            </div>

            <div class="info-card">
              <h3 style="color: #007bff; margin-top: 0; margin-bottom: 20px; font-size: 20px;">📋 Rental Summary</h3>
              
              <div class="info-grid">
                <div class="info-item">
                  <span class="info-label">Client Name:</span>
                  <div class="info-value">${contactData.name}</div>
                </div>
                
                <div class="info-item">
                  <span class="info-label">Website:</span>
                  <div class="info-value">${siteData.title}</div>
                </div>
                
                <div class="info-item">
                  <span class="info-label">Monthly Price:</span>
                  <div class="info-value">$${siteData.price}/month</div>
                </div>
                
                <div class="info-item">
                  <span class="info-label">Client Email:</span>
                  <div class="info-value">${contactData.email}</div>
                </div>
              </div>
              
              ${contactData.phone ? `
              <div class="info-item">
                <span class="info-label">Client Phone:</span>
                <div class="info-value">${contactData.phone}</div>
              </div>
              ` : ''}
            </div>

            <div class="info-card">
              <h3 style="color: #007bff; margin-top: 0; margin-bottom: 20px; font-size: 20px;">📅 Expiration Details</h3>
              
              <div class="info-item">
                <span class="info-label">Expiration Date:</span>
                <div class="info-value">
                  ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}
                </div>
                <div class="date-detail">
                  (${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric'
        })})
                </div>
              </div>
              
              <div class="info-item">
                <span class="info-label">Time Remaining:</span>
                <div class="info-value">
                  ${contactData.daysRemaining} day${contactData.daysRemaining !== 1 ? 's' : ''}
                  ${contactData.daysRemaining === 0 ?
            ' - <span class="highlight">Expires today!</span>' :
            contactData.daysRemaining <= 3 ?
                ' - <span class="highlight">Urgent attention required</span>' :
                ''}
                </div>
              </div>
              
              <div class="info-item">
                <span class="info-label">Exact Expiration Time:</span>
                <div class="info-value">
                  ${new Date(contactData.rentalEndDate).toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
            timeZoneName: 'short'
        })}
                </div>
              </div>
            </div>

            <div class="info-card">
              <h3 style="color: #007bff; margin-top: 0; margin-bottom: 20px; font-size: 20px;">⚡ Quick Actions</h3>
              
              <div class="button-container">
                <a href="${process.env.ADMIN_URL || 'http://localhost:3000/admin'}/contacts/${contactData._id}" 
                   class="button">
                   👁️ View in Admin Panel
                </a>
                
                <a href="mailto:${contactData.email}?subject=Renewal: ${siteData.title}&body=Dear ${contactData.name},%0D%0A%0D%0AYour rental for ${siteData.title} is expiring on ${new Date(contactData.rentalEndDate).toLocaleDateString()}.%0D%0A%0D%0APlease let us know if you'd like to extend your rental period.%0D%0A%0D%0ABest regards,%0D%0ARentalSite Team" 
                   class="button button-contact">
                   📧 Email Client
                </a>
              </div>
              
              ${contactData.phone ? `
              <div style="text-align: center; margin-top: 15px;">
                <span style="color: #6c757d; font-size: 14px;">📞 Quick Call:</span>
                <a href="tel:${contactData.phone}" style="color: #28a745; font-weight: 600; margin-left: 10px;">
                  ${contactData.phone}
                </a>
              </div>
              ` : ''}
              
              <div style="text-align: center; margin-top: 20px; font-size: 14px; color: #6c757d;">
                <p style="margin: 5px 0;">
                  <strong>Recommended action:</strong> Contact client within 24 hours
                </p>
                <p style="margin: 5px 0;">
                  <strong>Reminder:</strong> Client has already received expiration notification
                </p>
              </div>
            </div>
          </div>

          <div class="footer">
            <p>This is an automated notification from RentalSite Management System</p>
            <p>
              <strong>Notification ID:</strong> EXP-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}${String(new Date().getDate()).padStart(2, '0')}-${Math.random().toString(36).substr(2, 6).toUpperCase()}
            </p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
            <p>⏰ Generated on: ${new Date().toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        })}</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),
    rentalExpired: (contactData, siteData) => ({
        subject: `🔴 Rental Expired: ${siteData.title}`,
        html: `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: linear-gradient(135deg, #dc3545 0%, #c82333 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
                .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; }
                .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #dc3545; }
                .button { background: #dc3545; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; }
                .alert-box { background: #fff3cd; border: 2px solid #ffc107; padding: 15px; border-radius: 5px; margin: 15px 0; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🔴 Rental Period Ended</h1>
                    <p>Your website rental has expired</p>
                </div>
                
                <div class="content">
                    <div class="alert-box">
                        <h3 style="color: #856404; margin-top: 0;">⚠️ Important Notice</h3>
                        <p style="color: #856404;">
                            Your rental period for <strong>${siteData.title}</strong> has ended on 
                            ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
                    weekday: 'long',
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric'
                })}.
                        </p>
                    </div>
        
                    <div class="info-card">
                        <h3>📋 Rental Details</h3>
                        <p><strong>Website:</strong> ${siteData.title}</p>
                        <p><strong>Monthly Price:</strong> $${siteData.price}</p>
                        <p><strong>Expiration Date:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString()}</p>
                    </div>
        
                    <div class="info-card">
                        <h3>💳 Renew Your Rental</h3>
                        <p>To continue using ${siteData.title}, please make a payment to extend your rental period.</p>
                        <p><strong>Next Payment Amount:</strong> $${siteData.price}</p>
                        <div style="text-align: center; margin: 20px 0;">
                            <a href="mailto:${process.env.SMTP_FROM}?subject=Renewal Request: ${siteData.title}&body=Hello,%0D%0A%0D%0AI would like to renew my rental for ${siteData.title}.%0D%0A%0D%0AName: ${contactData.name}%0D%0AEmail: ${contactData.email}%0D%0A%0D%0APlease let me know the payment details." 
                               class="button">
                               📧 Request Renewal
                            </a>
                        </div>
                    </div>
        
                    <div class="info-card">
                        <h3>⚠️ Important Information</h3>
                        <p>Please note that access to the website will be suspended if payment is not received within 7 days.</p>
                        <p>For immediate assistance, please contact our support team.</p>
                    </div>
                </div>
        
                <div class="footer" style="text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px;">
                    <p>This is an automated notification from RentalSite</p>
                </div>
            </div>
        </body>
        </html>
`
    }),

    adminRentalExpired: (contactData, siteData) => ({
        subject: `🚨 RENTAL EXPIRED: ${contactData.name} - ${siteData.title}`,
        html: `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 700px; margin: 0 auto; padding: 20px; background-color: #ffffff; }
            .header { background: linear-gradient(135deg, #dc3545 0%, #bd2130 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
            .content { padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef; border-top: none; }
            .alert-box { background: #f8d7da; border: 2px solid #f5c6cb; border-left: 5px solid #dc3545; border-radius: 8px; padding: 20px; margin-bottom: 25px; }
            .info-card { background: #f8f9fa; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #6c757d; }
            .button { background: #dc3545; color: white; padding: 14px 32px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 16px; display: inline-block; margin: 0 10px; }
            .button-renew { background: #28a745; }
            .button-renew:hover { background: #218838; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚨 RENTAL EXPIRED</h1>
                <p>Client rental has ended - Immediate action required</p>
            </div>
            
            <div class="content">
                <div class="alert-box">
                    <h3 style="color: #721c24; margin-top: 0;">⚠️ URGENT: Rental Expired</h3>
                    <p style="color: #721c24;">
                        The rental for <strong>${siteData.title}</strong> has expired. 
                        Client status has been changed to <strong>payment_due</strong>.
                    </p>
                </div>
    
                <div class="info-card">
                    <h3 style="color: #343a40;">📋 Client Information</h3>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-top: 15px;">
                        <div>
                            <strong>Client:</strong> ${contactData.name}<br>
                            <strong>Email:</strong> ${contactData.email}<br>
                            ${contactData.phone ? `<strong>Phone:</strong> ${contactData.phone}<br>` : ''}
                        </div>
                        <div>
                            <strong>Website:</strong> ${siteData.title}<br>
                            <strong>Monthly Price:</strong> $${siteData.price}<br>
                            <strong>Total Paid:</strong> $${contactData.totalPaid || 0}
                        </div>
                    </div>
                </div>
    
                <div class="info-card">
                    <h3 style="color: #343a40;">📅 Expiration Details</h3>
                    <p><strong>Expiration Date:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            })}</p>
                    <p><strong>Expiration Time:</strong> ${new Date(contactData.rentalEndDate).toLocaleTimeString()}</p>
                    <p><strong>Days Overdue:</strong> <span style="color: #dc3545; font-weight: bold;">
                        ${Math.floor((new Date() - new Date(contactData.rentalEndDate)) / (1000 * 60 * 60 * 24))} days
                    </span></p>
                </div>
    
                <div class="info-card">
                    <h3 style="color: #343a40;">⚡ Required Actions</h3>
                    <div style="text-align: center; margin: 20px 0;">
                        <a href="${process.env.ADMIN_URL || 'http://localhost:3000/admin'}/contacts/${contactData._id}" 
                           class="button">
                           👁️ View in Admin
                        </a>
                        
                        <a href="mailto:${contactData.email}?subject=URGENT: Rental Expired - ${siteData.title}&body=Dear ${contactData.name},%0D%0A%0D%0AYour rental for ${siteData.title} has expired.%0D%0A%0D%0APlease contact us immediately to renew and avoid service interruption.%0D%0A%0D%0ABest regards,%0D%0ARentalSite Team" 
                           class="button button-renew">
                           📧 Contact Client
                        </a>
                    </div>
                </div>
            </div>
    
            <div class="footer" style="text-align: center; margin-top: 30px; padding: 20px; color: #6c757d; font-size: 14px;">
                <p>This is an automated notification from RentalSite Management System</p>
            </div>
        </div>
    </body>
    </html>
`
    }),
    // В emailService.js, добавьте после adminRentalExpired шаблона:

    paymentReceived: (contactData, siteData) => ({
        subject: `✅ Payment Received - ${siteData.title}`,
        html: `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                    .header { background: linear-gradient(135deg, #28a745 0%, #20c997 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
                    .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; }
                    .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #28a745; }
                    .success-icon { color: #28a745; font-size: 40px; text-align: center; margin: 20px 0; }
                    .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>✅ Payment Received</h1>
                        <p>Thank you for your payment</p>
                    </div>
                    
                    <div class="content">
                        <div class="success-icon">
                            ✓
                        </div>
                        
                        <div class="info-card">
                            <h3>📋 Payment Details</h3>
                            <p><strong>Amount:</strong> $${contactData.amount}</p>
                            <p><strong>For Website:</strong> ${siteData.title}</p>
                            <p><strong>Months Extended:</strong> ${contactData.months || 1}</p>
                            <p><strong>Payment Date:</strong> ${new Date().toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    })}</p>
                        </div>
            
                        <div class="info-card">
                            <h3>📅 New Rental Period</h3>
                            <p>Your rental has been extended until:</p>
                            <p style="font-size: 18px; font-weight: bold; color: #28a745;">
                                ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    })}
                            </p>
                            <p><strong>Next Payment Due:</strong> Approximately ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
                        month: 'long',
                        day: 'numeric',
                        year: 'numeric'
                    })}</p>
                        </div>
            
                        <div class="info-card">
                            <h3>📞 Support Information</h3>
                            <p>If you have any questions about your rental or payment, please contact our support team.</p>
                            <p><strong>Email:</strong> support@rentalsite.com</p>
                            <p><strong>Phone:</strong> +1 (555) 123-4567</p>
                        </div>
                    </div>
            
                    <div class="footer">
                        <p>This is an automated payment confirmation from RentalSite</p>
                        <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
            `
                }),

            // Также добавьте шаблон для уведомления админа о платеже:
    adminPaymentReceived: (contactData, siteData) => ({
        subject: `💰 Payment Received from ${contactData.name} - ${siteData.title}`,
        html: `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 700px; margin: 0 auto; padding: 20px; background-color: #ffffff; }
                    .header { background: linear-gradient(135deg, #28a745 0%, #20c997 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
                    .header h1 { margin: 0; font-size: 28px; font-weight: 600; }
                    .content { padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef; border-top: none; }
                    .info-card { background: #f8f9fa; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #28a745; }
                    .button { background: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>💰 Payment Received</h1>
                        <p>Client has made a payment for website rental</p>
                    </div>
                    
                    <div class="content">
                        <div class="info-card">
                            <h3 style="color: #28a745; margin-top: 0;">📋 Payment Summary</h3>
                            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-top: 15px;">
                                <div>
                                    <strong>Client:</strong> ${contactData.name}<br>
                                    <strong>Email:</strong> ${contactData.email}<br>
                                    ${contactData.phone ? `<strong>Phone:</strong> ${contactData.phone}<br>` : ''}
                                </div>
                                <div>
                                    <strong>Website:</strong> ${siteData.title}<br>
                                    <strong>Amount:</strong> $${contactData.amount}<br>
                                    <strong>Months:</strong> ${contactData.months || 1}
                                </div>
                            </div>
                        </div>
            
                        <div class="info-card">
                            <h3 style="color: #28a745;">📅 Rental Extension</h3>
                            <p><strong>Old End Date:</strong> Before payment</p>
                            <p><strong>New End Date:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    })}</p>
                            <p><strong>Extended By:</strong> ${contactData.months || 1} month${contactData.months !== 1 ? 's' : ''}</p>
                        </div>
            
                        <div class="info-card">
                            <h3 style="color: #28a745;">⚡ Quick Actions</h3>
                            <div style="text-align: center; margin: 20px 0;">
                                <a href="${process.env.ADMIN_URL || 'http://localhost:3000/admin'}/contacts/${contactData._id}" 
                                   class="button">
                                   👁️ View in Admin Panel
                                </a>
                            </div>
                        </div>
                    </div>
            
                    <div class="footer" style="text-align: center; margin-top: 30px; padding: 20px; color: #6c757d; font-size: 14px;">
                        <p>This is an automated payment notification from RentalSite Management System</p>
                    </div>
                </div>
            </body>
            </html>
            `
    })
};

// Main email sending function
// Обновите функцию sendEmailNotification в emailService.js:

export const sendEmailNotification = async (type, contactData, siteData = null, additionalData = {}) => {
    try {
        // Проверяем, существует ли такой шаблон
        if (!emailTemplates[type]) {
            console.error(`❌ Email template "${type}" not found`);
            return {
                success: false,
                error: `Email template "${type}" not found`,
                availableTemplates: Object.keys(emailTemplates)
            };
        }

        const transporter = createTransporter();

        // Добавляем дополнительные данные
        const dataWithExtras = {
            ...contactData,
            ...additionalData
        };

        const template = emailTemplates[type](dataWithExtras, siteData);

        // Определяем получателя в зависимости от типа письма
        let toEmail;

        switch(type) {
            case 'adminRentalExpiring':
            case 'adminRentalExpired':
            case 'adminPaymentReceived':
                toEmail = process.env.ADMIN_NOTIFICATION_EMAIL || process.env.SMTP_FROM;
                break;
            case 'rentalExpiringSoon':
            case 'rentalExpired':
            case 'paymentReceived':
                toEmail = contactData.email;
                break;
            case 'newRentalInquiry':
            case 'newContactMessage':
            case 'highPriorityAlert':
                toEmail = process.env.SMTP_FROM; // Отправляем админу
                break;
            default:
                toEmail = process.env.SMTP_FROM;
        }

        const mailOptions = {
            from: {
                name: 'RentalSite Notification System',
                address: process.env.SMTP_FROM
            },
            to: toEmail,
            subject: template.subject,
            html: template.html
        };

        console.log(`📤 Sending ${type} email to ${toEmail}...`);
        const result = await transporter.sendMail(mailOptions);
        console.log(`✅ ${type} email sent successfully:`, result.messageId);
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error(`❌ Error sending ${type} email:`, error);
        return { success: false, error: error.message };
    }
};
