import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create transporter - исправляем название функции
const createTransporter = () => {
    return nodemailer.createTransport({
        service: process.env.SMTP_SERVICE || 'gmail',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD
        }
    });
};

// Email templates (оставляем без изменений)
const emailTemplates = {
    newRentalInquiry: (contactData, siteData) => ({
        subject: `🎯 New Rental Inquiry: ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #667eea; }
          .badge { background: #667eea; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚀 New Website Rental Inquiry</h1>
            <p>A potential client is interested in renting your website</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>📋 Inquiry Summary</h3>
              <p><strong>Website:</strong> ${siteData.title}</p>
              <p><strong>Category:</strong> <span class="badge">${siteData.category}</span></p>
              <p><strong>Monthly Price:</strong> $${siteData.price}</p>
              <p><strong>Inquiry Date:</strong> ${new Date().toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>
            </div>

            <div class="info-card">
              <h3>👤 Client Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              ${contactData.company ? `<p><strong>Company:</strong> ${contactData.company}</p>` : ''}
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #667eea;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Actions</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Reply to Client</a>
                <a href="tel:${contactData.phone || ''}" class="button" style="background: #28a745;">📞 Call Client</a>
              </p>
              <p><small>Client timezone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}</small></p>
            </div>

            <div class="info-card">
              <h3>📊 Website Details</h3>
              <p><strong>Features:</strong> ${siteData.features?.join(', ') || 'No specific features listed'}</p>
              <p><strong>Technologies:</strong> ${siteData.technologies?.join(', ') || 'Not specified'}</p>
              ${siteData.demoUrl ? `<p><strong>Demo:</strong> <a href="${siteData.demoUrl}">View Live Demo</a></p>` : ''}
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Admin System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    newContactMessage: (contactData) => ({
        subject: `📧 New Contact Form Submission: ${contactData.subject || 'General Inquiry'}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff6b6b; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #ff6b6b; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📬 New Contact Message</h1>
            <p>Someone reached out through your website contact form</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>👤 Sender Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Subject:</strong> ${contactData.subject || 'Not specified'}</p>
              <p><strong>Received:</strong> ${new Date().toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        })}</p>
            </div>

            <div class="info-card">
              <h3>💬 Message Content</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #ff6b6b; white-space: pre-wrap;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Response</h3>
              <p>
                <a href="mailto:${contactData.email}?subject=Re: ${contactData.subject || 'Your Inquiry'}" class="button">
                  📧 Reply to Message
                </a>
              </p>
              <p><small>Response recommended within 24 hours</small></p>
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Contact System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    highPriorityAlert: (contactData, siteData) => ({
        subject: `🚨 HIGH PRIORITY: Urgent Rental Inquiry - ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff4757 0%, #ff3742 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #fff5f5; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff4757; border: 2px solid #ff4757; }
          .urgent-badge { background: #ff4757; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; display: inline-block; margin-bottom: 10px; }
          .button { background: #ff4757; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 5px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚨 URGENT: High Priority Inquiry</h1>
            <p>Immediate attention required for this rental request</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <div class="urgent-badge">⚠️ HIGH PRIORITY</div>
              <h3>📋 Urgent Rental Request</h3>
              <p><strong>Website:</strong> ${siteData.title} ($${siteData.price}/month)</p>
              <p><strong>Client:</strong> ${contactData.name} - ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>

            <div class="info-card">
              <h3>🎯 Immediate Actions Required</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Email Client</a>
                ${contactData.phone ? `<a href="tel:${contactData.phone}" class="button" style="background: #2ed573;">📞 Call Now</a>` : ''}
              </p>
              <p><strong>Response Time:</strong> Recommended within 1-2 hours</p>
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #fff1f1; padding: 15px; border-radius: 5px; border-left: 3px solid #ff4757;">
                ${contactData.message}
              </p>
            </div>
          </div>
        </div>
      </body>
      </html>
    `
    })
};

// Main email sending function
export const sendEmailNotification = async (type, contactData, siteData = null) => {
    try {
        const transporter = createTransporter();

        const template = emailTemplates[type](contactData, siteData);

        const mailOptions = {
            from: {
                name: 'RentalSite Notification System',
                address: process.env.SMTP_FROM
            },
            to: process.env.SMTP_FROM, // Send to admin email
            subject: template.subject,
            html: template.html
        };

        console.log('📤 Attempting to send email...');
        const result = await transporter.sendMail(mailOptions);
        console.log('✅ Email notification sent successfully:', result.messageId);
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error('❌ Error sending email notification:', error);
        console.error('❌ Error details:', error.message);
        return { success: false, error: error.message };
    }
};

// Test email configuration
export const testEmailConfig = async () => {
    try {
        const transporter = createTransporter();

        const mailOptions = {
            from: process.env.SMTP_FROM,
            to: process.env.SMTP_FROM,
            subject: '✅ RentalSite Email Test',
            html: `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h2 style="color: #64ffda;">🎉 Email Configuration Test</h2>
          <p>This is a test email from your RentalSite application.</p>
          <p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Status:</strong> ✅ Email system is working correctly</p>
        </div>
      `
        };

        console.log('🧪 Sending test email...');
        const result = await transporter.sendMail(mailOptions);
        console.log('✅ Test email sent successfully');
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error('❌ Test email failed:', error);
        console.error('❌ Test error details:', error.message);
        return { success: false, error: error.message };
    }
};