import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Create transporter
const createTransporter = () => {
    return nodemailer.createTransport({
        service: process.env.SMTP_SERVICE || 'gmail',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD
        }
    });
};

// Email templates (изменяем только subject в highPriorityAlert)
const emailTemplates = {
    newRentalInquiry: (contactData, siteData) => ({
        subject: `🎯 New Rental Inquiry: ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #667eea; }
          .badge { background: #667eea; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚀 New Website Rental Inquiry</h1>
            <p>A potential client is interested in renting your website</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>📋 Inquiry Summary</h3>
              <p><strong>Website:</strong> ${siteData.title}</p>
              <p><strong>Category:</strong> <span class="badge">${siteData.category}</span></p>
              <p><strong>Monthly Price:</strong> $${siteData.price}</p>
              <p><strong>Inquiry Date:</strong> ${new Date().toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>
            </div>

            <div class="info-card">
              <h3>👤 Client Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              ${contactData.company ? `<p><strong>Company:</strong> ${contactData.company}</p>` : ''}
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #667eea;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Actions</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Reply to Client</a>
                <a href="tel:${contactData.phone || ''}" class="button" style="background: #28a745;">📞 Call Client</a>
              </p>
              <p><small>Client timezone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}</small></p>
            </div>

            <div class="info-card">
              <h3>📊 Website Details</h3>
              <p><strong>Features:</strong> ${siteData.features?.join(', ') || 'No specific features listed'}</p>
              <p><strong>Technologies:</strong> ${siteData.technologies?.join(', ') || 'Not specified'}</p>
              ${siteData.demoUrl ? `<p><strong>Demo:</strong> <a href="${siteData.demoUrl}">View Live Demo</a></p>` : ''}
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Admin System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    newContactMessage: (contactData) => ({
        subject: `📧 New Contact Form Submission: ${contactData.subject || 'General Inquiry'}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff6b6b; }
          .footer { text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px; }
          .button { background: #ff6b6b; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📬 New Contact Message</h1>
            <p>Someone reached out through your website contact form</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>👤 Sender Information</h3>
              <p><strong>Name:</strong> ${contactData.name}</p>
              <p><strong>Email:</strong> ${contactData.email}</p>
              <p><strong>Subject:</strong> ${contactData.subject || 'Not specified'}</p>
              <p><strong>Received:</strong> ${new Date().toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        })}</p>
            </div>

            <div class="info-card">
              <h3>💬 Message Content</h3>
              <p style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 3px solid #ff6b6b; white-space: pre-wrap;">
                ${contactData.message}
              </p>
            </div>

            <div class="info-card">
              <h3>⚡ Quick Response</h3>
              <p>
                <a href="mailto:${contactData.email}?subject=Re: ${contactData.subject || 'Your Inquiry'}" class="button">
                  📧 Reply to Message
                </a>
              </p>
              <p><small>Response recommended within 24 hours</small></p>
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by RentalSite Contact System</p>
            <p>💼 <strong>RentalSite Business</strong> | Professional Website Rentals</p>
            <p>📍 ${new Date().getFullYear()} RentalSite. All rights reserved.</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    highPriorityAlert: (contactData, siteData) => ({
        subject: `🚨 URGENT: Rental Inquiry - ${siteData.title}`, // Убрали "HIGH PRIORITY"
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff4757 0%, #ff3742 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #fff5f5; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff4757; border: 2px solid #ff4757; }
          .urgent-badge { background: #ff4757; color: white; padding: 8px 16px; border-radius: 20px; font-weight: bold; display: inline-block; margin-bottom: 10px; }
          .button { background: #ff4757; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 5px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🚨 URGENT: Rental Inquiry</h1> <!-- Убрали "High Priority" -->
            <p>Immediate attention required for this rental request</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <div class="urgent-badge">⚠️ URGENT</div> <!-- Изменили текст бейджа -->
              <h3>📋 Urgent Rental Request</h3>
              <p><strong>Website:</strong> ${siteData.title} ($${siteData.price}/month)</p>
              <p><strong>Client:</strong> ${contactData.name} - ${contactData.email}</p>
              <p><strong>Phone:</strong> ${contactData.phone || 'Not provided'}</p>
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>

            <div class="info-card">
              <h3>🎯 Immediate Actions Required</h3>
              <p>
                <a href="mailto:${contactData.email}" class="button">📧 Email Client</a>
                ${contactData.phone ? `<a href="tel:${contactData.phone}" class="button" style="background: #2ed573;">📞 Call Now</a>` : ''}
              </p>
              <p><strong>Response Time:</strong> Recommended within 1-2 hours</p>
            </div>

            <div class="info-card">
              <h3>💬 Client Message</h3>
              <p style="background: #fff1f1; padding: 15px; border-radius: 5px; border-left: 3px solid #ff4757;">
                ${contactData.message}
              </p>
            </div>
          </div>
        </div>
      </body>
      </html>
    `
    }),
    rentalExpiringSoon: (contactData, siteData) => ({
        subject: `⏰ Rental Expiring Soon: ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #ff9f43 0%, #ff9f43 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
          .content { background: #fffaf0; padding: 30px; border-radius: 0 0 10px 10px; }
          .info-card { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #ff9f43; }
          .button { background: #ff9f43; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 10px 0; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>⏰ Rental Expiring Soon</h1>
            <p>Your website rental period is about to expire</p>
          </div>
          
          <div class="content">
            <div class="info-card">
              <h3>📋 Rental Details</h3>
              <p><strong>Website:</strong> ${siteData.title}</p>
              <p><strong>Monthly Price:</strong> $${siteData.price}</p>
              <p><strong>Expiration Date:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })}</p>
              <p><strong>Days Remaining:</strong> ${contactData.daysRemaining} days</p>
            </div>

            <div class="info-card">
              <h3>💳 Renew Your Rental</h3>
              <p>To continue using ${siteData.title}, please make a payment to extend your rental period.</p>
              <p><strong>Next Payment Amount:</strong> $${siteData.price}</p>
              <a href="mailto:support@rentalsite.com?subject=Renewal: ${siteData.title}" class="button">
                📧 Contact Support to Renew
              </a>
            </div>

            <div class="info-card">
              <h3>📞 Need Assistance?</h3>
              <p>If you have any questions about your rental or payment, please contact our support team.</p>
              <p><strong>Email:</strong> support@rentalsite.com</p>
              <p><strong>Phone:</strong> +1 (555) 123-4567</p>
            </div>
          </div>

          <div class="footer" style="text-align: center; margin-top: 30px; padding: 20px; color: #666; font-size: 12px;">
            <p>This is an automated reminder from RentalSite</p>
          </div>
        </div>
      </body>
      </html>
    `
    }),

    adminRentalExpiring: (contactData, siteData) => ({
        subject: `⚠️ Rental Expiring: ${contactData.name} - ${siteData.title}`,
        html: `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: #ff9f43; color: white; padding: 20px; text-align: center; }
          .content { background: #f8f9fa; padding: 20px; }
          .button { background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h2>⚠️ Rental Expiring Soon</h2>
          </div>
          <div class="content">
            <p><strong>Client:</strong> ${contactData.name}</p>
            <p><strong>Email:</strong> ${contactData.email}</p>
            <p><strong>Website:</strong> ${siteData.title}</p>
            <p><strong>Expires:</strong> ${new Date(contactData.rentalEndDate).toLocaleDateString()}</p>
            <p><strong>Days Remaining:</strong> ${contactData.daysRemaining}</p>
            <p><a href="${process.env.ADMIN_URL}/contacts/${contactData._id}" class="button">View in Admin Panel</a></p>
          </div>
        </div>
      </body>
      </html>
    `
    })
};

// Main email sending function
export const sendEmailNotification = async (type, contactData, siteData = null, additionalData = {}) => {
    try {
        const transporter = createTransporter();

        // Добавляем дополнительные данные
        const dataWithExtras = {
            ...contactData,
            ...additionalData
        };

        const template = emailTemplates[type](dataWithExtras, siteData);

        const mailOptions = {
            from: {
                name: 'RentalSite Notification System',
                address: process.env.SMTP_FROM
            },
            to: type === 'adminRentalExpiring'
                ? process.env.ADMIN_NOTIFICATION_EMAIL || process.env.SMTP_FROM
                : contactData.email,
            subject: template.subject,
            html: template.html
        };

        console.log(`📤 Sending ${type} email...`);
        const result = await transporter.sendMail(mailOptions);
        console.log(`✅ ${type} email sent successfully:`, result.messageId);
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error(`❌ Error sending ${type} email:`, error);
        return { success: false, error: error.message };
    }
};

// Test email configuration
export const testEmailConfig = async () => {
    try {
        const transporter = createTransporter();

        const mailOptions = {
            from: process.env.SMTP_FROM,
            to: process.env.SMTP_FROM,
            subject: '✅ RentalSite Email Test',
            html: `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h2 style="color: #64ffda;">🎉 Email Configuration Test</h2>
          <p>This is a test email from your RentalSite application.</p>
          <p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Status:</strong> ✅ Email system is working correctly</p>
        </div>
      `
        };

        console.log('🧪 Sending test email...');
        const result = await transporter.sendMail(mailOptions);
        console.log('✅ Test email sent successfully');
        return { success: true, messageId: result.messageId };

    } catch (error) {
        console.error('❌ Test email failed:', error);
        console.error('❌ Test error details:', error.message);
        return { success: false, error: error.message };
    }
};